### ISSUE TITLE
AreaConnection Implementation

### ISSUE THREAD

**Issue by zachtaylor** [zachtaylor/JPokemon#16]
I'm sort of stuck/confused on how to implement something here.

an Area represents some place a player can be; Route, City, etc. (those are the only two that I have imagined so far). Areas may have water to fish in, or buildings you can visit. 

AreaConnections are the transitions from one area to another. Sometimes, there are requirements to use an AreaConnection (such as having 2 gym badges, etc). I don't really understand how to implement that... 

Any sort of discussion might help

**Comment by arahlf** [comment]
I would implement it kind of like you described.  An area has 1-many AreaConnections.  Whenever the player navigates within the area, check to see if they're on an AreaConnection, and if they meet the requirements, let them continue on.

**Comment by zachtaylor** [comment]
The only difference i have is that areas have to have multiple connections, and area connections are like tunnels used to go to different areas. I'm not at graphics yet.

The problem i'm facing is i get it, but i can't imagine how to implement it, easily. The problem is I want to pass a requirement function to the AreaConnection in order to set it up.

I can just have a bunch of classes, all extending a base AreaConnectionRequirementChecker type thing, or I can enumerate and use a big switch on the type, just have huge enum type list... Do I use anonymous classes to sort of pass a function?

**Comment by arahlf** [comment]
So is an AreaConnection a type of Area where they can actually navigate around in, or is it just kind of like a door way?  Do you want AreaConnection to actually extend Area.

What do you need to use a function pointer for exactly?  The requirements checker could just be an interface, you're not bound to an inheritance tree that way then.

**Comment by zachtaylor** [comment]
An AreaConnection is not a descendent of Area. It's like a doorway.

In setting up Areas, my idea is to give each Area a list of AreaConnections which can be "used" to change the current area. Each AreaConnection may have a requirement, which is always a function of the player. I don't think there is a set standard for requirements.

Each function has to be unique. That's the problem.

**Comment by zachtaylor** [comment]
I think the best way to achieve this in Java is to pass anonymous classes which implement an interface. For example:

```
Area myarea = ...;

myarea.addConnection(new AreaConnection("Pewter City", new MyClass implements AreaConnectionRequirement {
  public boolean canPass(Player p) { return true; }
}));
```

**Comment by arahlf** [comment]
That's basically along the lines of what I was going to suggest.  You don't necessarily have to use anonymous classes though...  You could also move the canPass method right onto the AreaConnection.

**Comment by zachtaylor** [comment]
I never thought of that. It would be a lot better... thanks!
