### ISSUE TITLE
Code Refactor

### ISSUE THREAD

**Issue by zachtaylor** [zachtaylor/JPokemon#17]
I'm hoping to generate some discussion about an idea I've had. I'm imagining taking this project further than my original goal... My idea is a multi-player pokemon world. I only have a vague idea of what stands between the current code, and that.
1. The player object must contain ALL information relative to the player (no static data)
2. A separation layer between game code and game graphics

Beyond these two goals, i don't know what to do. The iteration goals (tentatively) are

Bellsprout: Properly implement 1 player (still no graphics)
Cubone: Implement local multiplayer (still no graphics)
Dratini: Implement graphics
Eevee: Implement hosted multiplayer

Any discussion would probably help.. :)

**Comment by shortstuffsushi** [comment]
A couple of starting questions.

Not sure what you mean with your point 1and static data.

Graphics and logic should always be separate, even in separate threads where possible. I think tjs is mostly covered currently since you're using swing.

In terms of the multiplayer, how do you see it workng in terms of user experience? Just walking around in the world and seeing people doing the same?

In terms of code, how do you imagine local working? What does 'local' mean in this context? How do you intend to communicate, peer to peer or client-server?

Just some starting thoughts

**Comment by zachtaylor** [comment]
Right now the player doesn't own enough, at least i don't think so. Battles manipulate parties, and circumvent the player for updates and messages, even choices. The player so far isn't used much.

That's exactly right, I'm imagining pokemon worlds where you can hangout with people, have battles on the fly, trade on the fly, etc. like a pokemon MMO

by local multiplayer, i mean setting up an additional GUI environment on the same machine, which is connected to a different player. Ideally, two players can then play on one JVM. It wouldn't be very practical... The next step in that direction would be allowing players to be on remote machines.

I really don't know much about peer to peer. I was imagining the game would come in two parts, a server and some kind of executable or java applet or even just an HTML5/JS environment (though i don't think that's practical). That way, anyone can set up a server and have their friends connect to them. Peer to peer might be worth looking into, simply cause I only understand it from a very high level.

**Comment by shortstuffsushi** [comment]
Peer to peer vs client server basically means each user maintains his and other players connection info (and I don't necessarily mean Player class) vs each player having minimal knowledge of what's going on,but rather sending in his info and subscribing to broadcasts from a central server.

Either way can work, you just need to do different setup around it.

**Comment by zachtaylor** [comment]
Is there a network congestion difference between p2p and client/server? Also, which would be better for my end goal?

I'm imagining each player keeping their save file, and using that as their credentials to "login" anywhere, so that their progress doesn't rely on any central server, and login is easy to do.
The other way I can think to do it is adding a password to each file, then the file name is the account name, for a client/server implementation. That server can allow file downloading so people can leave.

**Comment by shortstuffsushi** [comment]
I think client server might be better if you want persistence. P2P is more for a on and done sort of thing -- you play a match, then disconnect. MMO is obviously geared towards long term connect, disconnect, and reconnect later with your stats remembered.

In that way, a user wouldn't have a save, the server would knw about the user, position, stats, etc. It doesn't seem like you'd need a password for a user, you can just give a user a uuid and that'll make them uniquely recognizable.

To me it does seem like stats should be kind of an 'account' per server. It doesn't seem like you should be able to maintain a file locally and just pass that to any server you connect to.

**Comment by zachtaylor** [comment]
oh okay.. could it be possible to implement p2p for battles/trades? I think battles at least could be done that way, so they run client(ish) side, reducing strain on the server.

what is a uuid? 

I think the application would be more robust if your profile could migrate servers, but that's an old vice I have from private-server WoW.
