### ISSUE TITLE
Tools.askForInput Usage

### ISSUE THREAD

**Issue by shortstuffsushi** [zachtaylor/JPokemon#2]
Hi Zach,

I was just browsing through the code in the Tools.java, and noticed you're using the expected string up to index 6 for both this method below, and select move (as a cancel option). I don't know if you had the same intent in this method (to cancel) or if you just missed that, but index 6 would be out of bounds.

Also, rather than using the 'out of bounds' index to cancel, you could just modify the "ask for input" to (optionally) accept null, indicating they wish to cancel.

```
/**
* Return position of selected party member. Only show buttons for members
* that are != null.
*
* @param userparty The party to survey
* @return Position of Pokemon in party (0-5). -1 if cancel.
*/
  public static int selectFromParty(String message, Party userparty) {
    StringBuilder list = new StringBuilder("Party List:\n");
    String expectedOption = "0|1|2|3|4|5|6";
    int partyCount = 0;

    // We have to build the message to vary depending on
    // how many moves the active Pokemon has
    for (int i = 0; i < userparty.size(); ++i) {
      if (userparty.pkmn[i] != null) {
        partyCount++;
        list.append(i + ": " + userparty.pkmn[i].toString() + "\n");
      }
    }

    return Integer.parseInt(Tools.askForInput(message, list.toString(),
    // From 0 to 2 x The number of moves, - 1 to drop last |
        expectedOption.substring(0, partyCount * 2 - 1)));
  }
```

**Comment by zachtaylor** [comment]
Graham,

I agree with you. 6 would null pointer if the user could ever get to it. expectedOption.substring on that bottom line will only allow selection up to 5, so it isn't broken right now, it's just not correct. 

I don't quite understand using 'out of bounds' index to cancel. What do you mean? Currently, the user CANNOT cancel in selectFromParty

I'm also noticing that checking the party size iterates from 0 to number of entries, but only records the ones that aren't null. That's sort of redundant, and wrong. If there were any nulls, then there are entries after nulls, and those entries which are indexed higher than size()-1 won't appear.

**Comment by shortstuffsushi** [comment]
Addressing things from reverse, you're correct on the issue of intermittent nulls, which is why I've suggested a forced 'resort' on removal -- IE party occupants always occupy lowest index possible. It's a pretty minimal operation, and it would be difficult to support methods like this select method without it (well, short of just giving them GUI options, which I'm sure is the direction it's going).

I guess what I assumed you had INTENDED to do with the 6 was offer the user a cancel option, to which I had suggested that you all for null rather than allow for a "out-of-bounds" type of cancel option (Again, that's 0-5 indicates party selection, 6 indicates cancel). Rather than doing that, you could look for optionally allow the askForInput method to allow for nulls (which is what is returned when the user clicks on the X).

Some code for that might look as follows

```
  public static String askForInput(String title, String message,
                                   String expectedPattern, boolean allowCancel) {
    String input = "";

    while (input == "" ||
          (input == null && !allowCancel) ||
          !input.matches(expectedPattern)) {
      input = JOptionPane.showInputDialog(null, message, title,  JOptionPane.QUESTION_MESSAGE); 
    }

    return input;
  }
```

**Comment by zachtaylor** [comment]
That sounds like it's just something we're going to have to do. There are lots of issues like that that we will need to fix eventually.

The other thing we can do is let JOptionPane throw an exception on pressing cancel, which I thought it did, catch it, and return null out of askForInput, else return the text.

Its fine by me whichever way it goes. You can make that change if you want. Mostly i don't want to deal with the cancel option, and the UI at this stage is more about getting from a to b, and less about enjoying the ride

**Comment by zachtaylor** [comment]
Not really relevant anymore
