### ISSUE TITLE
Hiatus

### ISSUE THREAD

**Issue by zachtaylor** [zachtaylor/JPokemon#26]
I recently discovered http://pokemmo.eu

As such, I will be going on indefinite hiatus from developing JPokemon

I plan to finish the Cubone iteration, since I'm so close...
I also plan to comment and JavaDoc heavily, so that the code is accessible to whoever may pick it up next

**Comment by shortstuffsushi** [comment]
This didn't happen, and isn't an issue.

**Comment by zachtaylor** [comment]
:(
