### ISSUE TITLE
XP Computation

### ISSUE THREAD

**Issue by zachtaylor** [zachtaylor/JPokemon#28]
Pokemon have a base value for experience. See branch `dev-betterxp`

**Comment by adfuhr** [comment]
Nice use of lab time lol

**Comment by zachtaylor** [comment]
haha. you're on github too punk

**Comment by adfuhr** [comment]
Now I am. Because I got an email update about jpokemon haha

**Comment by zachtaylor** [comment]
Oh really? Dang. I always forget that I'm spamming everyone who's subscribed.

**Comment by zachtaylor** [comment]
https://github.com/zachtaylor/JPokemon/commit/0867877087cbf97249ceb162b12e69e3fd8e2982 and https://github.com/zachtaylor/JPokemon/commit/785e64bd94c3de1f9e02d9bf035f7787a2d30000

Need help adding this to the database... @shortstuffsushi ?

**Comment by shortstuffsushi** [comment]
Simple as:

```
public static void main(String[] args) throws Exception {
    BufferedReader reader = new BufferedReader(new FileReader(new File("farmed_(...).txt")));

    String line;
    while ((line = reader.readLine()) != null) {
        System.out.println(line);
        line = line.replace("  ", " ");

        String[] pieces = line.split(" ");
        PokemonInfo info = PokemonInfo.get(Integer.parseInt(pieces[0]));
        info.xpyield = Integer.parseInt(pieces[1]); 

        SqlStatement.update(info).execute();
    }
  }
```
