### ISSUE TITLE
Stores

### ISSUE THREAD

**Issue by zachtaylor** [zachtaylor/JPokemon#39]
Players need to be able to buy things!
Specifically, an NPC should be able to trigger the Store state, where Players can buy/sell items.
This shopping architecture will probably closely resemble pokemon upgrade architecture

**Comment by zachtaylor** [comment]
Completely wrong. OP is such a dumbass.

It is probably a good idea to let stores dictate what their sale prices are, and what items they sell.
Furthermore, other things may be added in the future (ie minigames) which require player "state" to be effected.
These observations directly imply several things that will make the story huge.
1. If stores can behave differently (different items, different prices) you need to know which store a player is in
2. If you need to know what store a player is in, you also need to know what else they may be doing (ex a battle)
3. If you need to manage diverse player activities which may expand, you need a framework
4. This framework is completely server-level, and as such, the Player ADT shouldn't do much with it's activity

There is only this conclusion: PlayerState needs abstraction, so that different activities can be done, ie Battle, Store, Upgrade, Trade... etc. Players need a current activity or current ... thing ... they're doing.

Will open a new issue and link it

**Comment by zachtaylor** [comment]
#49

**Comment by JakeHP** [comment]
god dammit OP get your shit together.

I will implement a hidden gem in the store which allows the players last equipped pokemon to rob & mug everyone in the Store.
