### ISSUE TITLE
Understand how Issues work vs Wiki

### ISSUE THREAD

**Issue by zachtaylor** [zachtaylor/JPokemon#4]
I don't get it. :)

**Comment by arahlf** [comment]
What part don't you understand?  Issues are kind of like JIRA tickets, representing some kind of work to be done.  Wikis are more for documentation purposes.

**Comment by zachtaylor** [comment]
Okay. Can the wiki reference issues? Can issues reference the wiki?

**Comment by arahlf** [comment]
You could probably just reference them using hyperlinks.

**Comment by zachtaylor** [comment]
hmm. in both instances? The wiki seems RESTful, but issues seem a little more complicated?

*\* EDIT**
on test, issues are RESTful too
