### ISSUE TITLE
Allow Players to name their Rival

### ISSUE THREAD

**Issue by zachtaylor** [zachtaylor/JPokemon#44]
Probably make the rival name a part of the request to create.
This could later be solved in the client by doing the oak speech thing. Oak would ask for your name and rivals name, then you start in your bedroom.

**Comment by JakeHP** [comment]
Oak asking for you and your rivals name while in your bedroom? JPokemon - Rated M for mature.

**Comment by zachtaylor** [comment]
hahaha
PS : you're a contributor, you can mainline anything you want
