### ISSUE TITLE
Battle (lack of) termination

### ISSUE THREAD

**Issue by zachtaylor** [zachtaylor/JPokemon#47]
When a faster Pokemon dies, the battle does not end.
It seems that the battle only ends when the slower Pokemon dies...

**Comment by krswanson** [comment]
Hi, I just downloaded the JPokemon repository (great idea btw!).  I tried it out, and my L5 charmander fainted after fighting a L5 pikachu (which was faster than my charmander), and the battle did not appear to terminate. 
~Kristin

**Comment by zachtaylor** [comment]
Hi Kristin. Thank you so much for your interest!
I would like to ask a couple questions, if you wouldn't mind.

Which branch did you discover this issue on?
Were there any special circumstances? ie status ailment, charmander dealt itself the final blow, etc?

I was able to reproduce a (different?) bug on my local machine. When Charmander is paralyzed by the wild Pikachu, regardless of speed, the battle fails to terminate.

**Comment by krswanson** [comment]
I am using the master branch.  Yes, it does happen when charmander is paralyzed.  But when he is not paralyzed, if he gets down to zero hp remaining, I can still go on fighting.  Is that supposed to happen?

**Comment by JakeHP** [comment]
I think I know the issue krswanson. Try using one of these: http://pokemon.wikia.com/wiki/Parlyz_Heal

**Comment by zachtaylor** [comment]
No, that's not supposed to happen. I will be tackling this bug tonight, but have no idea what's going on with the paralysis issue yet.

**Comment by zachtaylor** [comment]
@Jakehp paralyz heals haven't been added yet

**Comment by zachtaylor** [comment]
I didn't mean to close it. Dang github doing that automatically.
I am pretty sure this is fixed. I have verified that the the faster pokemon fainting causes a battle termination.
I also can no longer reproduce the paralysis issue, and don't know if it's fixed or just sneaky.
